#!/usr/bin/env bash
# Display information about subdomains

dns_config () {
  echo "The subdomain $2 is a $(dig +short "$2.$1" | awk '{print $4}') record and points to $(dig +short "$2.$1" | awk '{print $1}')"
}

if [[ $# -eq 1 ]]; then
  for subdomain in www lb-01 web-01 web-02; do
    dns_config "$1" "$subdomain"
  done
elif [[ $# -eq 2 ]]; then
  dns_config "$1" "$2"
else
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi
