#!/usr/bin/env bash
# Display DNS information about subdomains

get_dns_info () {
    local subdomain=$1
    local domain=$2
    local record_type=$(dig "$subdomain.$domain" +short | awk '{print toupper($1)}')
    local destination=$(dig "$subdomain.$domain" +short)
    printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$destination"
}

if [ $# -eq 0 ]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

domain=$1

if [ $# -eq 1 ]; then
    subdomains=(www lb-01 web-01 web-02)
else
    subdomains=("$2")
fi

for subdomain in "${subdomains[@]}"; do
    get_dns_info "$subdomain" "$domain"
done
