#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

get_record_type() {
  dig +short -t "$1" "$2" | awk '{ if (NR==1) { print $1 } }'
}

get_destination() {
  dig +short "$1" "$2" | awk '{ if (NR==1) { print $1 } }'
}

if [[ -z $1 ]]; then
  echo "Error: domain argument is mandatory"
  exit 1
fi

if [[ -n $2 ]]; then
  subdomains=("$2")
else
  subdomains=("www" "lb-01" "web-01" "web-02")
fi

for subdomain in "${subdomains[@]}"; do
  record_type=$(get_record_type "$subdomain" "$1")
  if [[ -z $record_type ]]; then
    echo "Subdomain $subdomain does not exist for domain $1"
    continue
  fi
  destination=$(get_destination "$subdomain" "$1")
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
done
