#!/usr/bin/env bash

# This script transfers a file from a client to a server using scp.

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1


# Transfer the file to the server using scp
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

echo "File transferred successfully to $ip."

fi
