#!/usr/bin/env bash

# This script installs and configures Nginx on an Ubuntu machine to return "Hello World!" at the root URL.

# Install Nginx
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y nginx

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html
# Restart Nginx to apply changes
service nginx start
