#!/usr/bin/env bash
# This script configures an Nginx server to have a custom 404 page with the string "Ceci n'est pas une page" and returns an HTTP 404 error code

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/^    error_page 404/c\    error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
