#!/usr/bin/env bash
# This script installs and configures HAproxy on an Ubuntu machine 
#distribute traffic to two web servers using a roundrobin algorithm.

set -euo pipefail
sudo apt-get update
sudo apt-get install -y haproxy

sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 108440-web-01 108440-web-01:80 check
    server 108440-web-02 108440-web-02:80 check
EOF'

# Make sure that HAproxy can be managed via init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Check the status of HAproxy
sudo systemctl status haproxy

# Ensure the correct hostnames are set
sudo bash -c 'cat <<EOF >> /etc/hosts
127.0.0.1 108440-web-01
127.0.0.1 108440-web-02
EOF'

# Reload the hosts file
sudo systemctl reload nscd

# Check the hostnames
sudo hostnamectl
