#!/usr/bin/env bash
# This script installs and configures HAproxy on an Ubuntu machine to send traffic to two web servers using a roundrobin algorithm.

# Install HAproxy
apt-get update
apt-get install -y haproxy

# Configure HAproxy
cat << EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 108440-web-01 52.87.219.241:80-web-01 check
    server 108440-web-02 54.242.162.151:80-web-02 check
EOF

# Check HAproxy configuration
haproxy -c -V -f /etc/haproxy/haproxy.cfg

# Set init script to manage HAproxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy service
service haproxy restart
