#!/usr/bin/env bash
# This script installs and configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy

printf %s "
frontend 108440-lb-01_front
        bind *:80
        mode http
        default_backend 108440-lb-01_back
backend 108440-lb-01_back
        balance roundrobin
        server  52.87.219.241:80 check
        server  54.242.162.151:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
