#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
