#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 of all the server's active IPv4 IPs
# fix Ubuntu container's to listen on port 80

new="80 default_server"
old="8080 default_server"
sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default

service nginx restart
