#!/usr/bin/env bash
# A script that accpets one argument and runs the whoami command 
#under the user passed as an argument

# Check if an argument was passed
if [[ $# -eq 0 ]]; 
then
  echo "Please provide a username as an argument."
  exit 1
fi

# Run whoami command as the specified user
sudo -u "$1" whoami
