#!/usr/bin/env bash
# A script that runs nginx as nginx user
#listening to all active ip on port 8080

# Change the user that Nginx runs as to nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change the permissions of the Nginx cache directory to the nginx user
chown -R nginx:nginx /var/cache/nginx

# Configure Nginx to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
